#!/bin/zsh
#
# This lets you quickly jump into a test project directory.
#
# Type:
#
#   t <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_t`. Typically I'm using it like:
#
#    t jerolan<tab>/bo<tab>
#
# ...to quickly jump into jerolan/boom, for example.

cd "$TEST_PROJECTS/$1"
