cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'koekeishiya/formulae'

brew 'awscli'
brew 'bat'
brew 'coreutils'
brew 'fzf'
brew 'grc'
brew 'htop'
brew 'hub'
brew 'neovim'
brew 'nvm'
brew 'mongodb'
brew 'postgres'
brew 'rbenv'
brew 'wget'
brew 'wifi-password'
brew 'wrk'
brew 'zsh'
brew 'yabai'
brew 'koekeishiya/formulae/skhd'

cask 'filezilla'
cask 'ngrok'
cask 'switchhosts'
cask 'java8'
cask 'fastlane'
