cask_args appdir: '/Applications'

tap 'shaunsingh/SFMono-Nerd-Font-Ligaturized'

brew 'bat'
brew 'coreutils'
brew 'eza'
brew 'fd'
brew 'fzf'
brew 'gh'
brew 'grc'
brew 'hub'
brew 'jq'
brew 'mas'
brew 'ripgrep'
brew 'starship'
brew 'tldr'
brew 'wget'
brew 'zoxide'

cask 'appcleaner'
cask 'brave-browser'
cask 'discord'
cask 'figma'
cask 'font-sf-mono-nerd-font-ligaturized'
cask 'hyper'
cask 'imageoptim'
cask 'keybase'
cask 'lastpass'
cask 'microsoft-edge'
cask 'openvpn-connect'
cask 'raycast'
cask 'steam'
cask 'the-unarchiver'
cask 'transmission'
cask 'visual-studio-code'

mas 'Xcode', id: 497799835
mas 'Pages', id: 409201541
